name: build

on:
  push:
    branches:
      - '**'
      - '!main'
    paths-ignore:
      - .github/workflows/*
      - .gitignore
      - LICENSE
      - README.md

jobs:
  build:
    uses: opengood-aio/central-workflows/.github/workflows/python-package-build.yml@python
    secrets:
      codecov-token: ${{ secrets.CODECOV_TOKEN }}
