name: coverage

on:
  workflow_dispatch:
    schedule:
      # Automatically run every Sunday at midnight
      - cron: '0 0 * * 0'
    branches:
      - main

jobs:
  coverage:
    uses: opengood-aio/central-workflows/.github/workflows/python-code-coverage.yml@python
    with:
      run-code-coverage: true
    secrets:
      codecov-token: ${{ secrets.CODECOV_TOKEN }}
