name: coverage

on:
  release:
    types:
      - published

jobs:
  coverage:
    uses: opengood-aio/central-workflows/.github/workflows/python-code-coverage.yml@python
    with:
      run-code-coverage: true
    secrets:
      codecov-token: ${{ secrets.CODECOV_TOKEN }}
