name: release

on:
  pull_request:
    types:
      - closed
      - labeled
    branches:
      - main
    paths-ignore:
      - .github/workflows/*
      - .gitignore
      - LICENSE
      - README.md

jobs:
  release:
    uses: opengood-aio/central-workflows/.github/workflows/python-py-pi-release.yml@python
    with:
      git-email: ${{ vars.GIT_EMAIL }}
      git-user: ${{ vars.GIT_USER }}
      git-name: ${{ vars.GIT_NAME }}
    secrets:
      py-pi-token: ${{ secrets.PY_PI_TOKEN }}
      codecov-token: ${{ secrets.CODECOV_TOKEN }}
      workflow-token: ${{ secrets.WORKFLOW_TOKEN }}
